name: bringin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.1+10

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.19
  get: 
  gap: ^2.0.1
  flutter_svg: ^2.0.5
  badges: ^3.0.3
  path_provider: ^2.0.14
  file_picker: ^5.2.6
  image_picker: ^0.8.7+5
  fluttertoast: ^8.2.1
  substring_highlight: ^1.0.33
  path: ^1.8.2
  intl: ^0.18.0
  sms_autofill: ^2.3.0
  flutter_native_image: ^0.0.6+1
  flutter_expanded_tile: ^0.3.7
  flutter_spinkit: ^5.2.0
  flutter_typeahead: ^4.3.8
  flutter_keyboard_visibility: ^5.4.1
  geolocator: ^9.0.2
  http: ^0.13.6
  uuid: ^3.0.7
  flutter_screenutil: ^5.7.0
  permission_handler: ^10.2.0
  wakelock: ^0.6.2
  url_launcher: ^6.1.11
  dash_chat_2:
   git:
     url: https://github.com/tanvirmahamudshakil/Dash-Chat-2-main.git
  awesome_dialog: ^3.0.2
  syncfusion_flutter_pdfviewer: ^21.2.6
  percent_indicator: ^4.2.3
  onesignal_flutter: ^5.0.0

  place_picker: ^0.10.0
  in_app_update: ^4.0.1
  socket_io_client: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  time_machine: ^0.9.17
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  notification_permissions: ^0.6.1
  dotted_border: ^2.0.0+3
  change_app_package_name: ^1.1.0
  aamarpay: ^1.0.6
  shimmer: ^3.0.0
  nested_scroll_views: ^0.0.7
  emoji_picker_flutter: ^1.6.1
  photo_view: ^0.14.0
  audioplayers: ^5.1.0
  pdf: ^3.8.2 
  printing: ^5.9.3 
  open_file: ^3.3.2
  lecle_downloads_path_provider: ^0.0.2+8
  share_plus: ^6.3.4
  cached_network_image: ^3.2.3
  flutter_slidable: ^3.0.0
  google_maps_flutter: ^2.4.0
  dotted_line: ^3.2.2
  app_links: ^3.4.3
  firebase_core: ^2.15.1
  uni_links: ^0.5.1
  




dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
# native_splash_screen
flutter_native_splash:
  color: "#0077B5"
  ios_content_mode: scaleAspectFill
  android_gravity: center
  fullscreen: true
  android: true
  ios: true
  web: false

#change_app_icon
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
#flutter pub run flutter_launcher_icons:main
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/seeker_default_avatar/
    - assets/svg/
    - assets/icon2/
    - assets/about_me_ex/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-Black.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Bold.ttf
        - asset: assets/fonts/Helvetica.ttf
        - asset: assets/fonts/Helvetica-light.ttf
        - asset: assets/fonts/Helvetica-ExtraLight.ttf

      

    
       
   
       
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages